### ISSUE TITLE
crash in the medias viewer

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1171] opened 2017-04-27 13:26 UTC
Marked as P2 because we cannot reproduce it.

https://riot.im/bugreports/listing/2017-04-24/201239/

reported by @brownc:matrix.org
Phone: ASUS_Z00A (227967daca 7.1.1 REL)

thread: main, Activity:im.vector.activity.VectorMediasViewerActivity, Exception: java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.get(ArrayList.java:411)
	at android.support.v4.view.ViewPager.getChildDrawingOrder(ViewPager.java:737)
	at android.view.View.populateAccessibilityNodeInfoDrawingOrderInParent(View.java:7040)
	at android.view.View.onInitializeAccessibilityNodeInfoInternal(View.java:6993)
	at android.view.ViewGroup.onInitializeAccessibilityNodeInfoInternal(ViewGroup.java:3069)
	at android.webkit.WebView.onInitializeAccessibilityNodeInfoInternal(WebView.java:2497)
	at android.view.View.onInitializeAccessibilityNodeInfo(View.java:6609)
	at org.chromium.content.browser.accessibility.BrowserAccessibilityManager.createAccessibilityNodeInfo(BrowserAccessibilityManager.java:4656)
	at org.chromium.content.browser.accessibility.BrowserAccessibilityManager$1.createAccessibilityNodeInfo(BrowserAccessibilityManager.java:118)
	at android.view.View.createAccessibilityNodeInfoInternal(View.java:6565)
	at android.view.View.createAccessibilityNodeInfo(View.java:6553)
	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
	at android.view.View.onInitializeAccessibilityEventInternal(View.java:6505)
	at android.webkit.WebView.onInitializeAccessibilityEventInternal(WebView.java:2504)
	at android.view.View.onInitializeAccessibilityEvent(View.java:6493)
	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:6358)
	at android.view.View.sendAccessibilityEventUnchecked(View.java:6343)
	at android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:23679)
	at android.view.View$SendViewStateChangedAccessibilityEvent.runOrPost(View.java:23712)
	at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:9475)
	at android.view.View.onFocusChanged(View.java:6226)
	at android.webkit.WebView.onFocusChanged(WebView.java:2575)
	at android.view.View.clearFocusInternal(View.java:6130)
	at android.view.View.unFocus(View.java:6163)
	at android.view.ViewGroup.unFocus(ViewGroup.java:996)
	at android.view.ViewGroup.unFocus(ViewGroup.java:998)
	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:735)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:4449)
	at android.view.ViewGroup.addView(ViewGroup.java:4258)
	at android.support.v4.view.ViewPager.addView(ViewPager.java:1413)
	at android.view.ViewGroup.addView(ViewGroup.java:4198)
	at im.vector.adapters.VectorMediasViewerAdapter.instantiateItem(VectorMediasViewerAdapter.java:414)
	at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:943)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1125)
	at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
	at android.support.v4.view.ViewPager$3.run(ViewPager.java:254)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:618)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6176)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Comment by sabrinaj** [comment] 2017-06-19 16:10
Duplicate of https://github.com/vector-im/riot-android/issues/1296

**Closed by sabrinaj** 2017-06-19 16:10 UTC
Labels: bug, P2
