### ISSUE TITLE
Add Voice input button

### ISSUE THREAD

**Issue by MurzNN** [vector-im/riot-android#1577] opened 2017-09-07 06:32 UTC
At now Riot don't have voice input button so we must use external software for voice input the message. Will be good to add integrated button for start voice input, like in WhatsApp:
![](https://user-images.githubusercontent.com/1190097/30068738-e7c44432-921b-11e7-815b-9479164588f9.png)
And after start typing - it replaced to Send button:
![](https://user-images.githubusercontent.com/1190097/30068749-f1bbe0f8-921b-11e7-8123-4e5bebb78eb8.png)

**Comment by jcgruenhage** [comment] 2018-03-25 07:50
Duplicate of #1395

**Comment by sim6** [comment] 2018-05-06 07:47
Any progress about this?

**Comment by sim6** [comment] 2018-07-27 07:33
Currently there is a configuration option named "Send voice message" that adds "Send voice" option on touch the clip. Thanks, but I think it needs to many taps.

**Comment by bmarty** [comment] 2018-08-27 13:45
Duplicate of #1237

**Closed by bmarty** 2018-08-27 13:45 UTC
Labels: P3, feature
