### ISSUE TITLE
The 'search' placeholder text is light green, whatever the tab colour

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#2134] opened 2018-04-04 23:29 UTC
So you end up with horrific green-on-orange text and similar.  Instead can we just make it light grey to indicate it's placeholder, or perhaps 50% transparent white?

**Comment by bmarty** [comment] 2018-09-03 08:27
Duplicate of #2010

**Closed by bmarty** 2018-09-03 08:27 UTC
