### ISSUE TITLE
riot crash when try to open any file in the room

### ISSUE THREAD

**Issue by progserega** [vector-im/riot-android#2638] opened 2018-10-03 23:21 UTC
If I press by file link - riot crash. On screenshot I try press on "Отчёт по ЗЭС.xlsx". This tihs occur only on android 8.0. I try on android 6.01, android 4 - file opened without any problem.

Steps to reproduce:

1. Send file to room (pdf or xlsx)
2. Press on this fule in this room
3. Riot crash

Riot version: 0.8.15 (G-b150)
Phone: Samsung Galaxy A5 (2017)
Android version: 8.0.0

Screenshot:
![screenshot_20181004-090522_riotim](https://user-images.githubusercontent.com/1297163/46444475-8473f500-c7b5-11e8-9c9e-bbc75301c521.jpg)

logcat:
[logcat.log](https://github.com/vector-im/riot-android/files/2444343/logcat.log)

**Comment by akanouras** [comment] 2018-10-05 16:05
Same here with some VCFs.

Luckily the file is already downloaded and available in the notification list or the Download folder.

Riot version: 0.8.15 (G-b150)
Phone: Xiaomi Mi A1 (2017)
Android version: 8.1.0 (AospExtended-v5.8-OFFICIAL)

**Comment by bmarty** [comment] 2018-10-08 09:35
Duplicate of #2573

**Closed by bmarty** 2018-10-08 09:35 UTC
