### ISSUE TITLE
Notification keeps remaining even all rooms are read

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#2028] opened 2018-03-02 15:16 UTC
reported by @westernheld:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/2049

**Comment by ylecollen** [comment] 2018-03-02 15:18
i don't reproduce the issue

Steps to reproduce
1 - receive a notified message
2 - get a notification
3 - Mark all as read

-> the notification disapparear

**Comment by westernheld** [comment] 2018-03-04 17:56
Hmm, i cant reproduce it either anymore.
It felt like an "fixed" entry at the notification area. I disabled the permission of riot in my Android System to send notifications. With this setting i have been remaining till today. Today i granted the permissions back to riot and it seems to work again. But i will keep track on that and see if it will happen someday again.

**Comment by manuroe** [comment] 2018-03-14 17:14
>  i will keep track on that and see if it will happen someday again.

thanks @westernheld.
I close the issue for the moment. Re-open it if needed.

**Closed by manuroe** 2018-03-14 17:14 UTC
