### ISSUE TITLE
[e2e] Single megolm session used in two rooms

### ISSUE THREAD

**Issue by richvdh** [vector-im/riot-android#765] opened 2016-12-05 10:19 UTC
As reported at https://github.com/matrix-org/synapse/issues/1670

**Comment by richvdh** [comment] 2016-12-05 10:21
It looks like event id `$14809148653745127JvpkR:matrix.org`  (in room `!XLWyWCSLuZXbEICJOL:matrix.org`) was sent using a megolm session (`G12NLajfv46nT7jjxVs4ek8FLbRyYxBaoVaghdOIcJE`) which was meant for room `!NmnHdagwJzKENAFywg:matrix.org`.

**Comment by ylecollen** [comment] 2016-12-09 08:41
i don't see how to reproduce this issue.

**Comment by ylecollen** [comment] 2017-01-25 10:05
duplicate of https://github.com/vector-im/riot-android/issues/864

**Closed by ylecollen** 2017-01-25 10:05 UTC
Labels: bug, P2
