### ISSUE TITLE
mxc media urls not displaying correctly on Android client

### ISSUE THREAD

**Issue by mattboardman** [vector-im/riot-android#2677] opened 2018-10-22 17:02 UTC
Using latest play store version: 0.8.18 (G-b156)

When sending mxc urls the application fails to retrieve the associated media and defaults to a placeholder image:

![riot](https://user-images.githubusercontent.com/18381175/47306500-3acb3d00-d5f2-11e8-8099-9e93683c9bc7.png)

Issue doesn't exist for the web client.

**Comment by alphapapa** [comment] 2018-11-04 09:46
Happening to me now with 0.8.17 (G-b155).  More details:

* Several weeks ago, a friend of mine reported the same problem, however at that time, I did not experience the same problem.  i.e. in the same chat room, image messages I sent showed up properly, but my friend saw this placeholder instead.  We were both using Riot on Android.
* I *have not* upgraded Riot on my phone since before this problem started happening.  A few weeks ago, it was working fine.  Now it's not.  The Riot Android client version is the same.
* Some other image messages in the same room are displayed properly.
* Here is an image event that does not display properly in Riot Android.  I sent this message with my Emacs client, matrix-client.el.  It displays properly in Riot Web.
```
{
  "origin_server_ts": 1541324108985,
  "sender": "@alphapapa:matrix.org",
  "event_id": "$1541324108525807wnrHm:matrix.org",
  "content": {
    "body": "File: derp.png",
    "url": "mxc://matrix.org/osleejswECEABOBICxLmuROV",
    "msgtype": "m.image"
  },
  "type": "m.room.message",
  "unsigned": {
    "age": 433811
  },
  "room_id": "!CNimHBuXVeVipfenOX:matrix.org"
}
```
* Here is an event with the same image in the same room, but uploaded with Riot Web.  Riot Android displays it properly:
```
{
  "origin_server_ts": 1541324683154,
  "sender": "@alphapapa:matrix.org",
  "event_id": "$1541324683527302vuGXz:matrix.org",
  "content": {
    "body": "derp.png",
    "info": {
      "mimetype": "image/png",
      "thumbnail_info": {
        "mimetype": "image/png",
        "h": 150,
        "w": 300,
        "size": 14825
      },
      "h": 150,
      "thumbnail_url": "mxc://matrix.org/xYRmmRsfJnOvdasrQXtfvnEL",
      "w": 300,
      "size": 14107
    },
    "msgtype": "m.image",
    "url": "mxc://matrix.org/MeRazWQXcKcbqFQBuVykDohZ"
  },
  "type": "m.room.message",
  "unsigned": {
    "age": 208,
    "transaction_id": "m1541324682845.0"
  },
  "room_id": "!CNimHBuXVeVipfenOX:matrix.org"
}
```

**Comment by alphapapa** [comment] 2018-11-04 10:08
More info:

* While adjusting the keys sent in the image event, to test which one(s) cause Riot Android to display the image properly, I noticed that some of the testing events cause Riot Android to display the wrong image event in place of the correct one.  For example, this event causes Riot Android to display an earlier image event from the same room.
```
{
  "origin_server_ts": 1541325624540,
  "sender": "@alphapapa:matrix.org",
  "event_id": "$1541325624529607wFbqG:matrix.org",
  "content": {
    "body": "File: derp.png",
    "thumbnail_info": {
      "mimetype": "image/png",
      "h": 300,
      "w": 150,
      "size": 16238
    },
    "url": "mxc://matrix.org/bMxPqeHsGtbkapHkFlsGRPgv",
    "thumbnail_url": "mxc://matrix.org/bMxPqeHsGtbkapHkFlsGRPgv",
    "msgtype": "m.image",
    "size": 16238
  },
  "type": "m.room.message",
  "unsigned": {
    "age": 183
  },
  "room_id": "!CNimHBuXVeVipfenOX:matrix.org"
}
```
In fact, scrolling back through the history of a room which I've used to test image uploading and other things for months, I see the same image repeated over and over, in place of the images that should be displayed, sometimes interspersed with the placeholder image.  It seems that Riot Android is caching certain images or events and is displayed that cached event/image when it can't correctly parse an image event.  

Note that these incorrectly displayed images from months ago were displayed correctly at the time; it's only now that Riot Android is failing to display them.

**Comment by alphapapa** [comment] 2018-11-04 10:15
After further testing, it appears that the Riot Android client does not properly handle image events that do not specify the MIME-type of the image.  For example, this event displays properly:
```
{
  "origin_server_ts": 1541326369414,
  "sender": "@alphapapa:matrix.org",
  "event_id": "$1541326369531416vuRWt:matrix.org",
  "content": {
    "body": "File: derp.png",
    "info": {
      "mimetype": "image/png"
    },
    "msgtype": "m.image",
    "url": "mxc://matrix.org/CXTpnJlAsFRQRIIwODlkjjTo"
  },
  "type": "m.room.message",
  "unsigned": {
    "age": 659
  },
  "room_id": "!kgaJfqZYgdFFJhgROi:matrix.org"
}
```
But this event includes everything except the main image MIME-type, and for it, Riot Android displays either a placeholder or an earlier image event from the same room:
```
{
  "origin_server_ts": 1541326251168,
  "sender": "@alphapapa:matrix.org",
  "event_id": "$1541326251531130rcfcO:matrix.org",
  "content": {
    "body": "File: derp.png",
    "info": {
      "h": 150,
      "w": 300,
      "size": 14229
    },
    "thumbnail_info": {
      "mimetype": "image/png",
      "h": 150,
      "w": 300,
      "size": 14229
    },
    "url": "mxc://matrix.org/JJuHTdOLNGBHhjquJFXdbnjC",
    "thumbnail_url": "mxc://matrix.org/JJuHTdOLNGBHhjquJFXdbnjC",
    "msgtype": "m.image"
  },
  "type": "m.room.message",
  "unsigned": {
    "age": 193
  },
  "room_id": "!kgaJfqZYgdFFJhgROi:matrix.org"
}
```

**Comment by mattboardman** [comment] 2018-11-22 18:19
So can you elaborate why the mxc url doesnt have a mime type associated in the message body?

**Comment by tulir** [comment] 2018-11-23 15:10
Seems like a duplicate of #2666

**Comment by alphapapa** [comment] 2018-12-06 01:31
Possibly, however it seems that in this case, it's specifically the mimetype that's required, not the info list generally.

**Comment by bmarty** [comment] 2018-12-28 16:43
duplicate of #2666 (and fixed)

**Closed by bmarty** 2018-12-28 16:43 UTC
