### ISSUE TITLE
Missing Access Token

### ISSUE THREAD

**Issue by akashpal-21** [vector-im/riot-android#3411] opened 2020-01-10 12:49 UTC
![Screenshot_20200110-181617_1](https://user-images.githubusercontent.com/46517170/72154072-8f99d580-33a7-11ea-9210-a878eeddda1e.jpeg)

**Comment by vrozsas13** [comment] 2020-03-03 03:23
I noticed this too.

**Comment by swot-thomper** [comment] 2020-04-26 03:21
Can't figure out why this is happening.
I can see no other threads about it have received any kind of response from devs

**Comment by bmarty** [comment] 2020-05-05 12:07
Duplicate of #3404

**Closed by bmarty** 2020-05-05 12:07 UTC
