### ISSUE TITLE
Notification configuration UI

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#341] opened 2016-07-25 22:39 UTC
As per vector-web

**Comment by ylecollen** [comment] 2016-07-26 14:44
The android client already manages the notifications but it doesn't support the three states.
Such three states settings is not common (on Android or IOS)

![screenshot_2016-07-26-16-39-36](https://cloud.githubusercontent.com/assets/8971031/17142352/21ada21c-5350-11e6-962f-66bc23e23cb6.png)

**Comment by Mikaela** [comment] 2017-09-22 07:22
I think this can be called as duplicate of https://github.com/vector-im/riot-android/issues/472 based on that issue being more detailed and referenced to even if this one is older?

**Comment by matthijskooijman** [comment] 2018-04-18 07:32
I believe this issue is fixed and can be closed, notification settings now properly support On/Off/Noisy.

**Comment by bmarty** [comment] 2018-12-28 12:35
@matthijskooijman yes indeed :)

**Closed by bmarty** 2018-12-28 12:35 UTC
Labels: P3, enhancement
