### ISSUE TITLE
Add Gboard gifs support

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1581] opened 2017-09-08 06:56 UTC
reported by @yj:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/990

**Comment by Zjemm** [comment] 2017-11-02 20:00
Yesss

**Comment by cwmke** [comment] 2018-02-17 07:41
This is working for me on Android 8.1. Is it still not working on your devices?

**Comment by bmarty** [comment] 2019-01-04 13:55
Duplicate of #1516

**Closed by bmarty** 2019-01-04 13:55 UTC
Labels: P3, feature
