### ISSUE TITLE
Multiple Accounts / Identities

### ISSUE THREAD

**Issue by codedust** [vector-im/riot-android#693] opened 2016-11-11 12:58 UTC
It would be cool to be able to sign in to two different homservers to communicate with multiple identities. Currently, only one identity can be used. I'd like to communicate in some chats using my nickname and use my real name in other chats.

**Comment by pganssle** [comment] 2016-11-30 17:22
I think this is a critical feature for me if I'm going to join open chat rooms. I don't necessarily want my personal identity tied up with my identity on freenode or on a random chat room.

Ideally, you'd be able to sign in, client-side, on multiple accounts (either on the same or different homeservers), and when joining a new room, you'd have a pop-up or something that says, "Join as?" with a list of your identities.

**Comment by ikogan** [comment] 2017-01-30 04:17
Same, there are multiple contexts in which I would like to use Riot. Multiple identities (all with their own connection information) is pretty crucial.

**Comment by Matrixcoffee** [comment] 2017-02-09 18:19
This is a duplicate of #120

**Comment by richvdh** [comment] 2017-02-15 14:05
yes it is

**Closed by richvdh** 2017-02-15 14:05 UTC

**Comment by End-to-End-is-the-way** [comment] 2019-11-26 20:19
A crucial feature. For me, it would be very important to separate the ID I use for work from then one I use for family and friends.
