### ISSUE TITLE
Odd linkification bug with trailing slash

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#865] opened 2017-01-19 15:54 UTC
First url has the trailing slash **ex**cluded, second url has it **in**cluded.

https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/%2414848404413576911UCFdP:matrix.org

**Comment by WGH-** [comment] 2018-01-02 18:58
I've recently encountered this bug in private chat. The trailing slash "disconnects" from the URL on Riot Android. Both parties observe the issue. However, on the web client, the link appear normally.

What's really odd is that I'm unable to reproduce it. I tried sending the same message, both from web and mobile client, and it worked fine this time.

**Comment by bmarty** [comment] 2019-01-22 11:47
Many linkification cases contain issue (reported by nepugia): I increase the priority

![screenshot_20190119-204531](https://user-images.githubusercontent.com/3940906/51533644-c8156c00-1e43-11e9-83f7-19da8f5d5e63.png)

**Comment by BillCarsonFr** [comment] 2019-02-27 12:53
Regarding the trailing slash, in fact when the trailing slash it at the end of the text it will be part of the link, if it's not at the end (e.g. before a space) it will be excluded.

This is the standard behaviour of TextView autoLink (see Linkify).

Linkify will also only detect web urls with the following protocols http|https|rtsp, as well as web url with no protocol. -> Explains why goopher:// foo:// file:// mailto: are not recognized.

**Closed** 2019-03-06 13:17 UTC
Labels: P2, bug, ftr-linkification
