### ISSUE TITLE
Riot client hangs on video call end

### ISSUE THREAD

**Issue by RuralYak** [vector-im/riot-android#3311] opened 2019-09-16 20:26 UTC
Hello,

Video calls hang on the passive side. When you press hang up button video call ends ok on your side, but second participant sees frozen client. This is big issue since not all users know how to terminate hung application making them reboot device

Riot for android 0.9.6

Steps:

1. Make video call via homeserver with coturn instance
2. Hang up
3. Check remote side
ER: Call should end up normally
AR: Call screen displays last captured frame with, client does not react

Thank you.

**Comment by root562** [comment] 2019-09-23 02:44
I can confirm this. But in my case it happens randomly no matter which party does the hangup. Upon hangup sometimes the one doing the hangup crash. Sometimes the other party crash. Sometimes both crash. Sometime both hangup just fine. This has happen on the current version 0.9.6 and also the previous version. If there is no fast solution maybe somebody can suggest a workaround. Check also https://github.com/vector-im/riot-android/issues/501
This problem was three years ago but seems to me related.

**Comment by root562** [comment] 2019-09-23 07:04
Tracing the Riot 0.9.6 code for the bug. It happens at CallsManager.Java, onHangup(). mActiveCall.hangup() cause the program to crash. This is a call to SDK. The code is not in Riot 0.9.6. Can someone doing the matrix-android-sdk check what is happening inside IMXCall.hangup()?
How do I forward this to matrix-android-sdk thread?

**Comment by awesome-manuel** [comment] 2019-12-11 08:27
Increasing minSdkVersion to 21 fixes the problem for me.

**Comment by vmario89** [comment] 2020-01-04 00:36
Hi, have a similar issue hanging up video call. I have following situation

- Riot Android Client A with access to camera and microphone calls Riot Web (Browser) Client B by **Video Call**. Client B has no physically installed camera but only microphone. Client A calls B and B gets the request. B accepts the request but Riot recognizes the missing camera. B automatically disconnects from the call. Client A freezes forever while the "ring ring" sound runs all the time until the app is killed hardly by Android operating system.

**Comment by rajil** [comment] 2020-01-14 05:15
@awesome-manuel Is there a apk available with "minSdkVersion to 21"?

**Comment by awesome-manuel** [comment] 2020-01-14 12:36
@rajil no, actually increasing the minSdkVersion did somehow result in less hangs, but the problem is not gone.

**Comment by bmarty** [comment] 2020-02-24 18:09
Fixed in version 0.9.10

**Closed by bmarty** 2020-02-24 18:09 UTC
