### ISSUE TITLE
[Feature request] voice message support

### ISSUE THREAD

**Issue by wjhtinger** [vector-im/riot-android#1395] opened 2017-07-01 08:21 UTC
user can send & receive  the  voice message

**Comment by ClarkeCC** [comment] 2017-07-06 02:32
+1 iOS / users in general would appreciate this.

**Comment by gudbes** [comment] 2018-03-12 22:11
+1 This option would be so cool.Is it planned soon?

**Comment by jcgruenhage** [comment] 2018-03-25 09:45
duplicate of #1237

**Comment by t3chguy** [comment] 2018-06-02 23:44
duplicate indeedily

**Closed** 2018-08-27 13:45 UTC
Labels: P3, feature
