### ISSUE TITLE
Android phones show "Network Error"

### ISSUE THREAD

**Issue by bobobo1618** [vector-im/riot-android#951] opened 2017-02-17 16:25 UTC
Case 1:
- Use Riot on a Google Pixel, running Android 7.1.1 (as of issue), on T-Mobile for several months without issue
- Open Riot this morning
- Riot shows progress bar at top of screen indefinitely, fails to send messages (shows greyed out for a while, then tells me messages have failed)

Case 2:
- Uninstall Riot from above phone
- Install Riot from Play Store 
- Open Riot
- Riot shows pretty flashing logo in landscape for some reason, then a toast with "Network Error"

Evidence that this is not really a network error:
- Everything else on the device works
- I can ping the homeserver etc.
- I can open https://riot.im/app in a browser on the same device, which functions correctly
- I can reproduce on a second phone, which is identical but for being on Project Fi
- My tablet is for some reason unaffected

I'm not near something with ADB right now but I'm capturing a bugreport which will have Logcat details I can add later.

**Comment by bobobo1618** [comment] 2017-02-17 16:30
Since reading back I see I didn't make it very clear, in Case 2, Riot didn't even get to the login screen. It continued to show the blinking logo and spinning wheel.

Also, for some reason, as of now, the issues have disappeared.

I'll leave this bug open as I feel that it's possible some kind of service was down and given that the service in question was not my homeserver, everything should have continued functioning.

**Comment by bobobo1618** [comment] 2017-02-17 16:36
> for some reason, as of now, the issues have disappeared

This seems to be due to my phone connecting to a wifi network. When disconnected the issue persists. My theory is that Riot is attempting to connect to something other than my homeserver (which is accessible on the device, tested in a browser) and failing.

**Comment by ylecollen** [comment] 2017-02-20 13:01
bobobo1618  : The network error messages might be triggered when a network request failed with a timeout error i.e the client did not get any response from the server within 30 seconds.

Last week, we have had many server issues (matrix.org).

It might also be the GCM registration.
Could you check if you still have this issue by now ?
Could you send a bug report if you reproduce it ?

**Comment by bobobo1618** [comment] 2017-02-21 06:51
I haven't been able to reproduce since so I suspect it may be related to the matrix.org issues.

> It might also be the GCM registration.

Would this require a network request to something other than my homeserver or Google itself? Is it intended that this block the client from starting up or running at all?

**Comment by ylecollen** [comment] 2017-02-21 06:56
Sorry, the GCM registration does not lock anymore the application starting.

it would have been nice to find what locked the launching.

I close this issue because it cannot be reproduced.

**Closed by ylecollen** 2017-02-21 06:56 UTC
Labels: bug, P2

**Comment by z3ntu** [comment] 2018-02-18 10:49
![screenshot_20180218-102518](https://user-images.githubusercontent.com/3768500/36350950-c836ab10-14a1-11e8-9f22-df7ce5d219a8.png)
Could this be the same issue?
