### ISSUE TITLE
Riot breaks links if message contains numbers

### ISSUE THREAD

**Issue by xoxys** [vector-im/riot-android#2891] opened 2019-01-22 16:05 UTC
This is maybe a bit special case. If I create a link with markdown the results are as expected. The `Test1234/1234` is correctly displayed as a link:
![image](https://user-images.githubusercontent.com/3391958/51547567-de80ef00-1e66-11e9-8021-8159cf20eefa.png)

I am using the [Drone CI plugin](https://github.com/drone-plugins/drone-matrix/blob/68bb1dd6355cd65fb75ea138789c84d4da0963d8/plugin.go#L91-L100) which sends me the Status from my CICD system to matrix channel. This plugin uses gomatrix to send a short text and a link to the ci system as message type org.matrix.custom.html. The result is:
![image](https://user-images.githubusercontent.com/3391958/51547694-16883200-1e67-11e9-9f8f-465545162b03.png)

Riot breaks the link which is `ansible/xoxys.matrix#2c0b65eb` and only links `65` and i can open the number with my call app. Riot-Web displays the link correctly:
![image](https://user-images.githubusercontent.com/3391958/51547849-5d762780-1e67-11e9-825f-5098ed954553.png)

The source code looks also good to me:
```
"content": {
    "body": "Status: **_success_**<br/> Build: [ansible/xoxys.matrix#2c0b65eb](https://server.com/ansible/xoxys.matrix/34) (master) by xoxys",
    "msgtype": "m.notice",
    "format": "org.matrix.custom.html",
    "formatted_body": "<p>Status: <strong><em>success</em></strong><br/> Build: <a href=\"https://drone.rknet.org/ansible/xoxys.matrix/34\" rel=\"nofollow\">ansible/xoxys.matrix#2c0b65eb</a> (master) by xoxys</p>\n"
  },
```

Is there a way to work around this and get the links working on Android client?

**Comment by xoxys** [comment] 2019-01-22 19:22
Thanks for your reply. But why does it work if i write it in markdown and why does it break with HTML over the API? :) 

is there a way to send markdown formatted messages with the api?

**Comment by bmarty** [comment] 2019-01-23 09:02
Yes, you're right, markdown link should be handled correctly

**Comment by BillCarsonFr** [comment] 2019-02-28 15:40
I can't reproduce, if I send the following message
```
"content": {
    "body": "Status: **_success_**<br/> Build: [ansible/xoxys.matrix#2c0b65eb](https://server.com/ansible/xoxys.matrix/34) (master) by xoxys",
    "msgtype": "m.notice",
    "format": "org.matrix.custom.html",
    "formatted_body": "<p>Status: <strong><em>success</em></strong><br/> Build: <a href=\"https://drone.rknet.org/ansible/xoxys.matrix/34\" rel=\"nofollow\">ansible/xoxys.matrix#2c0b65eb</a> (master) by xoxys</p>\n"
  }
```

The link is highlighted as expected.
But I can't manage to click it

**Comment by BillCarsonFr** [comment] 2019-03-05 16:52
On old devices (4.x) the bug is reproducible.
It is now fixed, on old device the link is not broken with numbers, and on all platform it is clickable as expected

**Comment by xoxys** [comment] 2019-03-05 17:08
My device is on Android 7.X and was also affected

**Closed** 2019-03-06 13:17 UTC
Labels: ftr-linkification
