### ISSUE TITLE
** Unknown inbound session id **

### ISSUE THREAD

**Issue by takiainen** [vector-im/riot-android#758] opened 2016-11-29 13:57 UTC
When e2e is enabled, and I view the room via browser, all previously encrypted messages show just the above mentioned error. Same happens if I reinstall Riot (or update to new version 0.62 --> 0.63 or simply just change to another rom and install 0.63 again. 

I also seems that if I write a message via browser, it comes with the same error to my android mobile client.

**Comment by croulibri** [comment] 2016-11-30 13:38
I face the same issue with desktop / Firefox on https://riot.im/app/ and Android version 0.62 then 0.63, still the same problem.
If non e2e enabled, then no problem, messages are readable whatever is the client used.

**Comment by ylecollen** [comment] 2016-11-30 17:34
1- it is not possible to see your previous messages after a login because the encryption is done for a deviceId. This deviceId is unique at each application login.

2- We're fixing some race conditions on the encryption : a message sent by the web client should be visible by the android client.

**Comment by croulibri** [comment] 2016-11-30 18:36
The problem is that messages sent by Android client are not readable either by me neither by the other participant in the room !
And I checked that messages sent by web client in encrypted room are not readable by Android Client, they have the same "Unknown inbound session id".
It seems that you can not use history at all in encrypted room. And you can not use encrypted room between web client and Android Client.

I am not specialist at all, but I have seen that XMPP + OMEMO allow me to have/read history of encrypted chat posted by different devices between two people, once I allow the ID of the different devices, while keeping the exchange of message encrypted.
Sure Riot/Matrix tteam will find a solution to that !

**Comment by takiainen** [comment] 2016-12-06 21:27
DeviceID changes after every login? I think this approach significantly weakens the usability. Isn't there any other way to handle it for e.g. pair the ID with username ?

**Comment by ara4n** [comment] 2016-12-06 21:37
The intention is in the near future you can share session key data 
between trusted devices, so it doesn't matter that they change ID & 
keypair all the time.  https://github.com/vector-im/riot-web/issues/2286 
etc.

https://blog.filippo.io/giving-up-on-long-term-pgp/ is an excellent 
description of why long-lived user ID keys are not necessarily a great idea.

**Comment by takiainen** [comment] 2016-12-16 15:43
After uninstalling version 0.63 and installing 0.64 all my previously encrypted messages are unreadable in all rooms. And I mean not only messages sent by others, but also my own messages! Sorry for repeating myself, but what use is there to have all these fancy rooms with history when everything is lost after an update? See attached image

**Comment by richvdh** [comment] 2017-01-24 10:18
encryption history should not be lost on an update. That might have been a bug in an earlier version (I guess you meant 0.6.3 and 0.6.4 - there is no 0.63/0.64).

**Comment by richvdh** [comment] 2017-01-24 10:19
oh, you uninstalled 0.6.3 before installing 0.6.4? That probably cleared your store. Don't do that if you don't want to lose history.

**Comment by richvdh** [comment] 2017-01-24 10:21
I don't think this bug is meaningful any longer, so I'm going to close it. See https://github.com/vector-im/riot-web/issues/2996 for an issue tracking all the causes of "Unknown inbound session id".

**Closed by richvdh** 2017-01-24 10:21 UTC
Labels: bug, P2

**Comment by takiainen** [comment] 2017-01-24 13:06
This bug appears even if I uninstall the latest version available from F-Droid (0.6.5) and then reinstall it: all encrypted messages in all encrypted rooms are replaced with ""Unable to decrypt: The sender's device has not sent us the keys for this message."  -message. 

So history is there, but it is useless.

**Comment by richvdh** [comment] 2017-01-24 13:20
yes, every time you uninstall the app, it will forget the encryption keys. That is not a bug.

**Comment by takiainen** [comment] 2017-01-24 13:54
What I also wonder is the long list of "devices" in "settings". See attached screenshot. It seems that everytime I use a browser to chat in encrypted room, a new device ID is created resulting in 30+ device ID's. Despite my computer and the browser remains the same.

**Comment by takiainen** [comment] 2017-01-24 13:56
Ok, so maybe I need to backup RIOT when flashing a new ROM (obviously I don't just uninstall and reinstall RIOT just for fun;)  )

**Comment by feld** [comment] 2017-01-30 15:04
I'm having this issue on iOS as well. I can't see messages from my other contacts in a group chat... it's like they need to send me their keys but hey haven't

**Comment by richvdh** [comment] 2017-01-30 17:14
@feld: as I said, see vector-im/riot-web#2996 for an issue tracking all the causes of "Unknown inbound session id".
