### ISSUE TITLE
With an external keyboard (on Android), there's no way to send a message using only the keyboard. Ctrl-enter does nothing, enter and shift-enter both break line.

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1279] opened 2017-06-06 06:34 UTC
reported by @lalomartins:matrix.org

**Comment by lalomartins** [comment] 2017-06-06 07:09
I'm watching this, so if whoever writes a PR needs a tester, ping me.

**Comment by Matrixcoffee** [comment] 2017-06-10 11:38
Too bad I'm only allowed to leave one thumb.

Have keyboard. Will test.

**Comment by sbts** [comment] 2017-06-12 03:56
This is definitely a duplicate of #220 can someone mark it as such please

**Closed** 2018-08-06 14:53 UTC
Labels: P2, enhancement
