### ISSUE TITLE
How to implement a Contacts Book?

### ISSUE THREAD

**Issue by wjhtinger** [vector-im/riot-android#1777] opened 2017-11-26 08:29 UTC
Why not has  a Contacts Book? I think this is mandatory feature for a IM APP. 
Does the server support this feature or not？

**Comment by ylecollen** [comment] 2017-11-28 07:21
@wjhtinger 
you have such feature on riot.
It is the third tab in the home page.

There is a "local address book" which lets you use your contacts book to invite them to a room (email only for now).

There is a remote search.

**Comment by wjhtinger** [comment] 2017-12-19 11:56
I think a Contacts Book based on user ID is more useful, just many user dont want to bind their email or something.
And can chat with the people in the Contacts Book freely, no need to invite him.

**Comment by JonasDralle** [comment] 2017-12-19 14:28
Direct chat is a bit wonky at the moment. A direct chat is basically a group chat with 2 participants.

I have one direct chat with all my contacts and it works.

**Comment by bmarty** [comment] 2019-01-02 10:22
Duplicate of #899

**Closed by bmarty** 2019-01-02 10:22 UTC
Labels: question
