### ISSUE TITLE
GIF playback when tapping on them is broken as of 0.8.7

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#2188] opened 2018-04-25 17:14 UTC
Says narispo

**Comment by soupbowl** [comment] 2018-05-19 03:54
I lost GIF playback on both of my phones with the 0.8.7 update.

Nexus 5 - android 6.0.1
Blackberry Keyone - android 7.1.1

**Comment by bmarty** [comment] 2018-05-29 08:28
Duplicate of #2168

**Closed by bmarty** 2018-05-29 08:28 UTC
