### ISSUE TITLE
Multiple ID

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [vector-im/riot-android#768] opened 2016-12-06 19:06 UTC
I've chatted with others about being able to login with multiple IDs/identities, simultaneously...  We'd like to separate that which is "NSFW", for example, from work and family things.  

Then, some have been cyberstalked.  Other IDs/account logins are good.  

And, we all wear different hats...  Don't want all the eggs in one basket, as is said.  

If we get the boss on-board wuth Matrix, we don't always want them to gave instant access to us, or know where in the Matrix, or where it's bridged, where we go.  

We saw this in the "coming soon", but now it's gone.

**Comment by ylecollen** [comment] 2016-12-07 12:25
the multi accounts management is planned but we have many things to fix / to improve before.

**Comment by Mikaela** [comment] 2017-01-30 15:23
Duplicate of https://github.com/vector-im/riot-android/issues/693 ?

**Comment by Matrixcoffee** [comment] 2017-02-09 18:22
Yes. Also duplicate of #120

**Comment by richvdh** [comment] 2017-02-15 14:06
yes

**Closed by richvdh** 2017-02-15 14:06 UTC
Labels: enhancement, P3
