### ISSUE TITLE
Please give an option to change or disable the sound notifications.

### ISSUE THREAD

**Issue by gibbousmoon100** [vector-im/riot-android#1272] opened 2017-06-06 05:31 UTC
Currently, my phone chirps every time my friend sends me a message (even if I am already staring at the desktop client on my screen).

Because of Android's limitations, if I want to stop this behavior, my current options are

1. Disable all sound notifications on my phone, and miss important alerts from other apps.  Including Skype calls!
2. Disable all notifications in Riot, and severely limit the application's usefulness on my phone.

I'd love for Google to fix this limitation, but unless and until they do, will you consider adding this as a feature in the Android app?

Thanks!

**Comment by ylecollen** [comment] 2017-06-06 06:22
Your device should not trigger notification if the messages have been read on the web client.
Notice that the webclient only sends read receipts if the user moves his mouse.
It might explain your issue.

You could also disable notifications for this room and add a notification rule for some specific words (there already is a rule for your name)

**Comment by gibbousmoon100** [comment] 2017-06-06 06:40
1. I use the desktop client.
2. Assuming your comment applies equally to the desktop client, the requirement to move the mouse (even while the window is open) may be a different issue worth opening.  The notification on my phone is immediate.  Staring at the screen and waggling my mouse the entire time is hardly an ideal workaround, even if it did work.
3. I can disable notifications.  That's not what I want to do.  I want to keep them enabled, so that the client is actually useable for me on Android without the phone yelling at me constantly.

**Comment by tliron** [comment] 2017-06-06 06:46
@ylecollen Most Android apps let you control sound notification specifically in addition to whether you want any notification to happen. Riot should do the same. As it stands, Riot is either loud notifications or none at all.

**Comment by gibbousmoon100** [comment] 2017-06-06 07:06
I opened a separate issue for desktop client coordination: https://github.com/vector-im/riot-android/issues/1283

**Comment by ylecollen** [comment] 2017-06-06 12:17
gibbousmoon100,
It is weird i don't reproduce your issue but i might be a race condition.

Ie if a message is received on the web and an android clients, the webclient should send a read receipt asap it gets the message.

When the android device is notified, it performs a catchup to retrieve the unread "notifiable" messages and triggers the notification.

Either the webclient did not send the read receipt or the read receipt was triggered after the android client performed its catchup.

**Comment by ylecollen** [comment] 2017-06-06 12:17
@tliron 
we have such settings.

**Comment by gibbousmoon100** [comment] 2017-06-06 13:53
The notifications are received simultaneously.  My phone chirps at precisely the same time the Windows desktop client makes a "message received" noise.

tliron stated my issue exactly.  I don't see the settings you are referencing.  I only see "Enable notifications for this device."  Could you please tell us where to find the setting to disable sound only?

Thanks!

**Comment by ylecollen** [comment] 2017-06-22 06:44
"race condition" means that the application behaviour might change if two (or more) events are received in the order you expect.

The sound notification can only be triggered on the webclient.

@tliron, it is planned feature to manage it on mobile client.

**Comment by matthijskooijman** [comment] 2017-07-16 14:55
I believe this is essentially a duplicate of #1176?

**Closed** 2018-02-13 12:05 UTC
