### ISSUE TITLE
Clicking on an alias in a message causes "Cannot rejoin an empty room" every time

### ISSUE THREAD

**Issue by turt2live** [vector-im/riot-android#2042] opened 2018-03-05 17:27 UTC
This only happens on riot-android. I have v0.8.1 (google play) installed.

I can type `/join #theroom:domainc.om`, but tapping the alias in a message *always* gives me "Cannot rejoin an empty room".

**Comment by turt2live** [comment] 2018-03-05 17:32
![image](https://user-images.githubusercontent.com/1190097/36989992-89f444dc-2060-11e8-958d-815083fc906c.png)

Another victim

**Comment by anoadragon453** [comment] 2018-03-08 19:56
Also getting this on clicking a room in a pill.

**Comment by Tyuoli** [comment] 2018-03-19 08:40
I installed version v0.8.1 of Riot-Android and I can not reproduce the bug. In any case, I managed to join the room by clicking on its alias in a message, even if I left the room or if I rejected an invitation.

If you are on a server other than matrix.org, I'm afraid that the problem comes from server federation.

**Comment by turt2live** [comment] 2018-03-19 13:09
I am on a different server, but it has always worked until recently without server changes. Every other client is fine, so there seems to be a bug with how riot-android does the request.

**Comment by Tyuoli** [comment] 2018-03-19 14:05
Sorry, I couldn't reproduce this bug even with the pills. Could you create a rageshake please, so that we will can analyze the logs ?

**Comment by turt2live** [comment] 2018-03-19 14:21
sent (although it took about 15 minutes to send). Should be from `@travis:t2l.io`

**Comment by Tyuoli** [comment] 2018-03-19 14:44
Thanks, the room alias is null in the logs. I will analyze that.

**Comment by manuroe** [comment] 2018-03-19 15:18
The original error of the join request is `No known servers`. The code translates it to `Cannot rejoin an empty room`, which is not helpful.

But knowing this, the bug looks like https://github.com/vector-im/riot-web/issues/4251, which has been fixed by joining by the room alias instead of the room id.

We need to understand why Riot-Android does not use the room alias to join the room.

**Comment by Tyuoli** [comment] 2018-03-19 15:39
After analysis, it turns out that this bug is related to https://github.com/vector-im/riot-android/issues/2098. In this case, the code does not go through the right place and that's why the room alias is null.

**Closed by Tyuoli** 2018-03-19 15:39 UTC
Labels: P1, bug
