### ISSUE TITLE
In some cases, devices list is not shown in the settings

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#2409] opened 2018-07-03 17:58 UTC
Every time I open the settings from the menu, a toast is shown, saying java.lang.Boolean cannot be cast to java.lang.String.

![Screenshot of toast saying java.lang.Boolean cannot be cast to java.lang.String](https://matrix.org/_matrix/media/v1/download/matrix.org/RwtFPRScpkOIJVkEZQyYNeKW)

**Comment by bmarty** [comment] 2018-07-03 18:38
RageShake: https://github.com/matrix-org/riot-android-rageshakes/issues/2761

**Comment by bmarty** [comment] 2018-07-04 08:29
From the log:
```
06-29 14:18:29.644Z 1 EVENT/NAVIGATION: onResume Activity VectorSettingsActivity
06-29 14:18:29.648Z 1 D/RestAdapterCallback: Trigger the event [threePIDs]
06-29 14:18:29.662Z 2563 D/NetworkConnectivityReceiver: ## isConnected() : true
06-29 14:18:29.697Z 1 D/RestAdapterCallback: Trigger the event [getPushers]
06-29 14:18:29.710Z 1 D/NetworkConnectivityReceiver: ## isConnected() : true
06-29 14:18:31.485Z 1 D/VectorApp: onActivitySaveInstanceState im.vector.activity.VectorHomeActivity@424db3d0
06-29 14:18:31.488Z 1 D/VectorApp: onActivityStopped im.vector.activity.VectorHomeActivity@424db3d0
06-29 14:18:34.144Z 1 D/NetworkConnectivityReceiver: ## isConnected() : true
06-29 14:18:34.146Z 1 D/MXFileStore: Set setThirdPartyIdentifiers
06-29 14:18:34.147Z 1 D/MXMemoryStore: setThirdPartyIdentifiers : commit
06-29 14:18:34.148Z 1 D/MXFileStore: ++ Commit
06-29 14:18:34.152Z 1 D/MXFileStore: -- Commit
06-29 14:18:34.169Z 1 D/NetworkConnectivityReceiver: ## isConnected() : true
06-29 14:18:34.544Z 1 D/RestAdapterCallback: ## Succeed() : [getDevicesListInfo]
06-29 14:18:34.545Z 1 D/NetworkConnectivityReceiver: ## isConnected() : true
06-29 14:18:34.551Z 1 E/RestAdapterCallback: ## succeed() : onSuccess failed java.lang.Boolean cannot be cast to java.lang.String
06-29 14:18:36.000Z 1 D/RestAdapterCallback: ## Succeed() : [getPushers]
```

**Comment by bmarty** [comment] 2018-07-04 09:31
Hi @Matrixcoffee,

First of all, you see this toast and can report this error thanks to this commit: https://github.com/matrix-org/matrix-android-sdk/commit/cd9b5519d721c3352bb1bc5d442d830df489b1ea. Before, exception was ignored. So that a good point 👍. I'll try to log the stack trace, cause the log is a bit short.

That said, I'm trying to find the root cause of the issue.

Do you see the Device list in the settings screen?

**Comment by Matrixcoffee** [comment] 2018-07-04 14:20
@bmarty I only see current device info. There is no device list visible in settings.

**Comment by bmarty** [comment] 2018-07-06 13:54
RageShake: https://github.com/matrix-org/riot-android-rageshakes/issues/2761

Permalink: https://riot.im/app/#/room/#riot-android:matrix.org/$1530816583115342iPIuv:matrix.org

**Comment by bmarty** [comment] 2018-07-06 13:56
https://riot.im/app/#/room/#riot-android:matrix.org/$1530819480125365zRqiI:matrix.org

**Comment by bmarty** [comment] 2018-07-13 12:04
Waiting for PR about logging exception stack trace to be merged

**Comment by bmarty** [comment] 2018-07-20 13:46
PR has been merged, waiting for RageShake from @Matrixcoffee

**Comment by Matrixcoffee** [comment] 2018-07-28 08:42
Done. Apologies for the delay - was held up by #2456

**Comment by bmarty** [comment] 2018-08-06 12:01
https://github.com/matrix-org/riot-android-rageshakes/issues/2895

**Comment by bmarty** [comment] 2018-08-06 14:53
And here is the full log, thanks to @Matrixcoffee RS:

```
07-28 08:36:27.221Z 1 E/RestAdapterCallback: ## succeed() : onSuccess failed java.lang.Boolean cannot be cast to java.lang.String
07-28 08:36:27.224Z java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:224)
	at android.preference.Preference.getPersistedString(Preference.java:1458)
	at android.preference.EditTextPreference.onSetInitialValue(EditTextPreference.java:157)
	at android.preference.Preference.dispatchSetInitialValue(Preference.java:1374)
	at android.preference.Preference.onAttachedToHierarchy(Preference.java:1165)
	at android.preference.PreferenceGroup.addPreference(PreferenceGroup.java:177)
	at im.vector.fragments.VectorSettingsPreferencesFragment.buildDevicesSettings(VectorSettingsPreferencesFragment.kt:2210)
	at im.vector.fragments.VectorSettingsPreferencesFragment.access$buildDevicesSettings(VectorSettingsPreferencesFragment.kt:87)
	at im.vector.fragments.VectorSettingsPreferencesFragment$refreshDevicesList$1.onSuccess(VectorSettingsPreferencesFragment.kt:2124)
	at im.vector.fragments.VectorSettingsPreferencesFragment$refreshDevicesList$1.onSuccess(VectorSettingsPreferencesFragment.kt:2119)
	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.success(RestAdapterCallback.java:169)
	at org.matrix.androidsdk.rest.callback.RestAdapterCallback$1.onSuccess(RestAdapterCallback.java:142)
	at org.matrix.androidsdk.rest.callback.DefaultRetrofit2ResponseHandler.handleResponse(DefaultRetrofit2ResponseHandler.java:13)
	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.handleResponse(RestAdapterCallback.java:137)
	at org.matrix.androidsdk.rest.callback.RestAdapterCallback.onResponse(RestAdapterCallback.java:130)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5299)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
	at dalvik.system.NativeStart.main(Native Method)
```

**Closed** 2018-08-08 14:33 UTC
