### ISSUE TITLE
change quickly between multiple accounts

### ISSUE THREAD

**Issue by maninthemiddle01** [vector-im/riot-android#1079] opened 2017-03-29 08:59 UTC
Hello,
thank you for your great app :)
Would it be possible to add an option to switch quickly between multiple accounts? e.g. if I have a public account for rooms and a private account for chats with friends?
Thank you :)

**Comment by ylecollen** [comment] 2017-03-29 12:42
duplicate of https://github.com/vector-im/riot-android/issues/576

**Closed by ylecollen** 2017-03-29 12:42 UTC
