### ISSUE TITLE
searching for a correct username yields no results

### ISSUE THREAD

**Issue by RoughCurve** [vector-im/riot-android#2745] opened 2018-11-26 20:46 UTC
You have to press "invite by id" to start a chat.

**Comment by RoughCurve** [comment] 2018-11-26 23:07
https://github.com/vector-im/riot-android/pull/2610 it seems a fix is implemented?

**Comment by turt2live** [comment] 2018-12-06 21:00
Duplicate of https://github.com/vector-im/riot-web/issues/6599 or https://github.com/vector-im/riot-web/issues/7373

**Closed by turt2live** 2018-12-06 21:00 UTC
