### ISSUE TITLE
[SailfishOS] Pictures sent to encrypted room become placeholders, cannot download

### ISSUE THREAD

**Issue by ivilata** [vector-im/riot-android#812] opened 2016-12-26 23:29 UTC
Hi, I'm using Riot 0.6.5 from FDroid (ebddfd4) via Android compatibility in SailfishOS.  When in an unencrypted room, I'm able to receive pictures from other room members without problems.  However, when encryption is enabled in the room and someone sends a picture, after a few seconds I only get a black and white, schematic placeholder picture.  When I select it and the (barely visible) download pie completes, I only get a fully black picture with unresponsive share and download buttons, although in some very rare occasions I can actually get the picture, share and download it (the thumbnail remains schematic, though).

I've ruled out an issue in the server (I run my own) since if I also connect to the same room using ``riot-web``, I'm able to see the images without problems.  Other participants can get the pictures as expected.

What could be the reason for this behaviour?  Is there something I could try to provide more info on the issue?

Thanks!

**Comment by rocket-pig** [comment] 2017-01-08 19:31
I think my bug is a duplicate of yours.
https://github.com/vector-im/riot-android/issues/840

**Comment by rocket-pig** [comment] 2017-01-08 23:04
I found using a KitKat "4.4.4" ROM i was able to load picture attachments. What is your android version?  There's a bit more in the linked issue above.

**Comment by ylecollen** [comment] 2017-01-13 07:20
ivilata
Could you send a bug report ?
I don't have a similar device to reproduce your issue.

**Comment by ylecollen** [comment] 2017-01-13 10:29
I don't have the bug report zip files in your bug report.

**Comment by ivilata** [comment] 2017-01-13 10:35
Umm, maybe since it's using the Sailfish mail client to send the email, something gets lost in the way.`:(`

May I use the option of sending via Riot itself? Where to? You may send me the address to ivan at selidor dot net if you don't want to publish it here.

Also, I'd like to include a screenshot of the room screen, but the app only allows me to send the report from the room list.

Thanks a lot for tracking this!

**Comment by ylecollen** [comment] 2017-01-13 10:37
-> create a room between us
-> rageshake the device to send a bug report

**Comment by ylecollen** [comment] 2017-03-31 07:15
Reported again by @ivan:selidor.net the 03/31/2017

According to the logs
MXEncryptAtt: ## decryptAttachment() :  Digest value mismatch 
It seems that there is an error while decrypting an attachment.

Without a device under SailfishOs, i cannot fix this issue.
We have many e2e unit tests (we tested under x86/ arm 32/64 bits). But, i suspect that there is an issue with the e2e lib

**Comment by ylecollen** [comment] 2017-04-03 12:45
duplicate of https://github.com/vector-im/riot-android/issues/1093

**Closed by ylecollen** 2017-04-03 12:45 UTC
Labels: bug, P2

**Comment by ivilata** [comment] 2017-04-06 10:00
It's probable that you are right, given the old Android compat support in SailfishOS. I'll check your fix of #1093 when a new version hits F-Droid and report back here.

Thanks a lot!

**Comment by ivilata** [comment] 2017-06-20 07:14
After installing 0.6.10 from F-Droid I can confirm that I can download images from encrypted rooms without issues. Thank you very much for your help!
