### ISSUE TITLE
images inserted via `![](mxc://<hs>/<cid>)` are not displayed

### ISSUE THREAD

**Issue by krombel** [vector-im/riot-android#1753] opened 2017-11-14 11:34 UTC
When you insert an already posted image via a `![](mxurl)` it gets rendered on riot-web as expected but android does not show anything. As reference: https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$151065487645gfRnn:msgs.tk

**Comment by Matrixcoffee** [comment] 2017-11-14 11:42
For security reasons, external images are not shown inside messages. However, if the image url starts with mxc:// it is actually safe to load and display.

**Comment by walle303** [comment] 2017-11-14 14:11
#1733 covers this

**Comment by ylecollen** [comment] 2017-11-14 15:02
duplicate of #1733

**Closed by ylecollen** 2017-11-14 15:02 UTC
Labels: feature, P3
