### ISSUE TITLE
rageshake should prompt you to enter an explicit problem report before trying to send a report

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#842] opened 2017-01-11 13:16 UTC
We should only ever submit rageshakes by email - sending from smtp or http-to-smtp within the app if needed, as otherwise we constantly lose the reports due to folks accidentally sending them into random matrix rooms, or worse sending them to public matrix rooms and leaking private stuff

**Comment by ylecollen** [comment] 2017-01-11 13:48
Some users don't want to send the bug reports by email because they don't want to provide their email address.

**Comment by ara4n** [comment] 2017-01-11 14:10
In which case we should provide an HTTP endpoint like we did with UC 
that Riot can hit to submit bug reports, rather than ending up with them 
scattered in random public rooms.

**Comment by ylecollen** [comment] 2017-01-11 17:29
The user cannot send a bug report but typing a bug description.

**Comment by Matrixcoffee** [comment] 2017-01-12 09:15
+1 on the http(s) endpoint. Not everyone has e-mail even configured on their phone.

**Comment by madduck** [comment] 2017-01-25 17:53
@ara4n woudln't it make most sense to have all reports be sent to a "report-bugs-here" matrix room? It would not alleviate #888, but it would also prevent random channels from being spammed.

**Comment by Matrixcoffee** [comment] 2017-01-25 18:05
The problem is that AFAIK the Matrix spec doesn't provide for write-only rooms.

Everybody would be able to see and open everybody else's bug reports. Not good.

**Comment by Kegsay** [comment] 2017-01-25 18:36
I am working on an HTTP endpoint.

**Comment by madduck** [comment] 2017-01-25 20:19
@Matrixcoffee agreed. If you see it like this, maybe you could comment on #888 too, which was closed…

@Kegsay great. There *is* something to be said about being able to share a bug report *right there* with anyone, so maybe this could still be a possibility for advanced users, but an HTTPs endpoint as default sounds sensible.

**Comment by Kegsay** [comment] 2017-02-08 11:53
An HTTPS endpoint is now running on riot.im which can receive bug reports. It was originally designed for riot-web reports, but will equally work with Android.

**Comment by ylecollen** [comment] 2017-02-17 13:29
fixed with https://github.com/vector-im/riot-android/commit/1b8ca8d898977a2b8c3d2ed0a54643a0d88d644c

**Closed by ylecollen** 2017-02-17 13:29 UTC
Labels: enhancement, P2
