### ISSUE TITLE
Trying to make a channel public crashes android application

### ISSUE THREAD

**Issue by fwsGonzo** [vector-im/riot-android#2698] opened 2018-11-01 19:27 UTC
I was trying to make a channel public on Android and it crashed constantly. I think the crashes have been delivered to you automatically, but just in case I am making this issue.

**Comment by bmarty** [comment] 2018-11-02 09:47
Yes, thanks, it's a duplicate of #2679

**Closed** 2018-11-02 09:48 UTC
