### ISSUE TITLE
Any number longer than 1 char is incorrectly linkified into a phone number

### ISSUE THREAD

**Issue by ara4n** [vector-im/riot-android#1995] opened 2018-02-19 00:34 UTC
See https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/$15190001513246035OzDQR:matrix.org

**Comment by bmarty** [comment] 2019-01-22 11:49
Duplicate of #1140

**Closed by bmarty** 2019-01-22 11:49 UTC
