### ISSUE TITLE
Video Calls hand up riot crached.

### ISSUE THREAD

**Issue by bartekn80** [vector-im/riot-android#3370] opened 2019-11-04 08:42 UTC
Welcome
I assumed all 0.9.x versions have a problem with video connections. Disconnecting the video connection causes the riot app to hang on Android.
In contrast, version 0.8.28a on fdriod does not have this problem. In any case, I did not pout.

**Comment by coderzstas** [comment] 2019-11-05 16:41
same for me , tested on op5 ( android version 9 lineageos ) , redmi5 ( android vesion 8.1 miui stock) , op6t ( android version 10 oxygen os stock )

**Comment by volter** [comment] 2019-11-17 13:05
Duplicate of #3311?

**Comment by bmarty** [comment] 2020-02-06 11:05
Yes see #3311

**Closed by bmarty** 2020-02-06 11:05 UTC
