### ISSUE TITLE
Ability to discard unsent messages in bulk

### ISSUE THREAD

**Issue by madduck** [vector-im/riot-android#884] opened 2017-01-23 21:51 UTC
Sent a few messages yesterday that could not get delivered, so now Riot asks me if I want to resend them.
![awqpiasavtvlmtdirwelpxco](https://cloud.githubusercontent.com/assets/195073/22224238/df48455a-e222-11e6-9645-baaed675922d.jpeg)
 I don't, or not in this case anyway.

I can go through scrollback and redact all messages to make the little reminder go away, but it'd be great too if I could press on the warning sign (like on iOS) and be given the option to delete them all.

Thanks for your consideration.

**Comment by ylecollen** [comment] 2017-01-24 07:20
Notice that even long tapping on the warning icon is not an obvious behaviour.

**Comment by Matrixcoffee** [comment] 2017-01-24 07:39
Maybe the message can be changed to "Messages not sent. [Options](https://github.com).'

Then, pressing "options" can pop up a menu with "Resend Now" and "Discard".

**Comment by ylecollen** [comment] 2017-01-25 10:01
duplicate of 
https://github.com/vector-im/riot-android/issues/793

**Closed** 2017-01-26 15:33 UTC
Labels: enhancement, P2
