### ISSUE TITLE
long icon press shortcut

### ISSUE THREAD

**Issue by 532910** [vector-im/riot-android#2949] opened 2019-02-15 10:17 UTC
Please add support for icon press shortcut
https://developer.android.com/guide/topics/ui/shortcuts/

The last or favorite rooms should be in the shortcut list. There also may be call actions there.

**Comment by bmarty** [comment] 2019-02-19 13:42
Duplicate of #2896
Please upvote for it!

**Closed by bmarty** 2019-02-19 13:42 UTC

**Comment by 532910** [comment] 2019-02-19 13:46
Sorry!
How should I upvote for it, just thumb up?

**Comment by bmarty** [comment] 2019-02-19 13:57
Yes :)
