### ISSUE TITLE
Riot 0.9.2 freezes on Android 4.4.4 

### ISSUE THREAD

**Issue by bahur142** [vector-im/riot-android#3219] opened 2019-07-20 09:06 UTC
Hello
I have 3 devices
 - Xiaomi Mi4 with Android 4.4.4
 - Samsung Galaxy Tab with Android 4.4.4
 - Samsung Galaxy S4 mini with Android 4.4.3

Riot isn't starting after upgrade to 0.9.2 from Play Store. All of them freezes after the logo and then black screen. I have tried to clean the cash, but nothing. I can not send bug report from the app itself, because isn't starting.
After uninstall/install, no change in behavior. This time stays on logo screen and nothing more.

I have also Xiaomi Mi6 with android 8.0 and it is OK after upgrade.

**Comment by 66point99** [comment] 2019-07-23 20:12
Can confirm this bug affects all our Jellybean and KitKat test devices. Same symptoms, as described by @bahur142

**Comment by chresan** [comment] 2019-07-24 20:02
Someone I know uses a Samsung Galaxy Note S2 with the latest Riot version. Same problem. After starting Riot a black screen appears. Nothing else happens.

**Comment by chresan** [comment] 2019-07-25 10:58
The problem is gone on Samsung Galaxy Note S2 with the update from today.

**Comment by BillCarsonFr** [comment] 2019-07-30 07:45
fixed in 0.9.3

**Closed by BillCarsonFr** 2019-07-30 07:45 UTC
