### ISSUE TITLE
strange contact search behavior

### ISSUE THREAD

**Issue by xavierle** [vector-im/riot-android#866] opened 2017-01-19 16:34 UTC
comparing to matrix

with riot client
to start a chat  with another user i need to write the complete ID
@username:homeserve.org

on matrix consoler
to create a room with another user
usualy i just need to write the username and the user is found

even if riot is nicer it makes it a bit unuseful

email invitation is not very usable neither

when the user have registered with an email.
sometimes it is a bit easier to find it but not always

**Comment by xavierle** [comment] 2017-01-19 22:39
i made a bit more testing about contact search

in fact once 2 contacts visited the same room the search can find them easily

but it seems there is no seach possibility by username on a same homeserver
the only way to discover new contact is by personnal email ....

this is strange as after 2 visitors are on the same room thant search is very easy

**Comment by xavierle** [comment] 2017-01-19 22:43
when you are connected on the homerserver = testserver.org
and that you search for ther username : bob

i would suggest that the user @bob:testserver.org si found

**Comment by ylecollen** [comment] 2017-01-23 10:08
duplicate of 876

**Closed by ylecollen** 2017-01-23 10:08 UTC
Labels: enhancement, P3

**Comment by Matrixcoffee** [comment] 2017-01-24 07:31
#876
