### ISSUE TITLE
Signatures of Google Firebase Analytics still exists in 0.8.13

### ISSUE THREAD

**Issue by ShadowRZ** [vector-im/riot-android#2527] opened 2018-08-14 10:35 UTC
See https://reports.exodus-privacy.eu.org/reports/21071/

**Comment by Tokodomo** [comment] 2019-03-11 17:17
Refer to #2481

**Comment by bmarty** [comment] 2019-03-13 10:58
Duplicate of #2481

**Closed by bmarty** 2019-03-13 10:58 UTC

**Comment by ShadowRZ** [comment] 2019-03-23 22:19
Sorry. 🙇
