### ISSUE TITLE
Auto completion for / command

### ISSUE THREAD

**Issue by bmarty** [vector-im/riot-android#2384] opened 2018-06-25 16:24 UTC
When user types /, it should be convenient to display the list of available commands in a popin, the same way we display completion for user name

**Comment by manuroe** [comment] 2018-06-26 08:56
@bmarty, this is a duplicate of https://github.com/vector-im/riot-android/issues/247, no?

This is a long waiting feature...

**Comment by bmarty** [comment] 2018-06-26 09:14
Sorry, haven't checked for any existing issue

**Comment by bmarty** [comment] 2018-07-16 15:25
Audrey, it's maybe not long to implement, re-using the popup we already have to suggest users

**Closed** 2018-08-07 13:59 UTC
