### ISSUE TITLE
Add voice messages feature

### ISSUE THREAD

**Issue by megrf** [vector-im/riot-android#2378] opened 2018-06-24 10:50 UTC
We are using Riot as a corporate chat.
Using voice messages would be very convenient in some work situations.
It would be great if you add this feature. 

![voicemessage](https://user-images.githubusercontent.com/40538279/41818343-7cbe4748-77b5-11e8-87d9-30f061126527.jpg)

**Comment by tleydxdy** [comment] 2018-06-25 03:48
this function is already merged

**Comment by megrf** [comment] 2018-06-25 05:00
@tleydxdy sorry for a stupid question. But what do you mean by "merged"?

**Comment by bmarty** [comment] 2018-06-25 08:16
Hi @megrf, a workaround for this feature will be available soon on Andorid app: it will allow you to record a voice message with an external application and send it to a Room.

**Comment by progserega** [comment] 2018-07-13 23:05
This is good, but more nicely will be use native record in riot. User need more then 4 taps for voice record via external application.
And this record  have not preview in android riot:
![screenshot_20180714-085629](https://user-images.githubusercontent.com/1297163/42717513-e92efa5a-8744-11e8-96b3-34210a1b752c.png)
In web riot otherwise is good preview:
![web](https://user-images.githubusercontent.com/1297163/42717523-f8fefa02-8744-11e8-82ea-7ff15afa5272.png)

**Comment by sim6** [comment] 2018-07-27 07:39
See also #1577 #1395 #1237

**Comment by progserega** [comment] 2018-08-14 07:31
Today I describe to user how he can record voice record:
1. Press "attach button"
2. Select in menu "Send voice"
3. Select voice record app (press to it)
4. Press key "record" in voice app - record voice.
5. Press "stop" for stop record voice.
6. Press "Ok" for select and send voice to riot.

Then user ask me: "Why? Why it is so hard?" :-) 

I sink more wanted simply one key "record voce" - press it - and voice recording, release - stop recording and send to room.
More users want this features...
Thank you!

**Comment by bmarty** [comment] 2018-08-22 09:06
This feature has to be considered as a meta feature across all Riot/Matrix universe.
Maybe @lampholder can add this to the roadmap?

**Comment by bmarty** [comment] 2018-08-22 09:08
Duplicate of #1237

**Closed by bmarty** 2018-08-22 09:08 UTC
Labels: UX, feature

**Comment by deepakzero** [comment] 2020-07-22 19:11
@bmarty  how to add voice voice message feature in app. pls tell me sir
