### ISSUE TITLE
Support audio messages

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#1874] opened 2018-01-10 07:26 UTC
reported by @anne:synapse.monkz.de
https://github.com/matrix-org/riot-android-rageshakes/issues/1834
Only one suggestion: would it be possible to send language files? As with Whatsapp. Press and hold the recording button, speak and send. Sometimes that would be useful if you do not want to type in a longer message

**Comment by ylecollen** [comment] 2018-01-10 07:26
https://github.com/matrix-org/riot-android-rageshakes/issues/1834

**Comment by t3chguy** [comment] 2018-06-02 23:44
Duplicate of https://github.com/vector-im/riot-android/issues/1237

**Closed** 2018-08-27 13:44 UTC
Labels: P3, feature
