### ISSUE TITLE
Links in messages of type m.notice are visible but unclickable

### ISSUE THREAD

**Issue by Matrixcoffee** [vector-im/riot-android#2687] opened 2018-10-26 16:52 UTC
See https://matrix.to/#/!GnEEPYXUhoaHbkFBNX:matrix.org/$1540571614126260WAoWg:matrix.org for example.

This applies only to formatted body links. If the link is generated from the plain text body, it works.

**Comment by tulir** [comment] 2019-02-15 14:21
Duplicate of #2281

**Closed** 2019-02-19 13:43 UTC
Labels: bug
