### ISSUE TITLE
Riot currently doesn't support split screen multitasking. It would be nice if it could

### ISSUE THREAD

**Issue by ylecollen** [vector-im/riot-android#2026] opened 2018-03-02 15:10 UTC
reported by @haskal:matrix.org
https://github.com/matrix-org/riot-android-rageshakes/issues/2053

**Comment by tulir** [comment] 2018-03-05 19:37
Duplicate of #1832?

**Comment by manuroe** [comment] 2018-03-14 17:13
true

**Closed by manuroe** 2018-03-14 17:13 UTC
