### ISSUE TITLE
Send Text With Enter Key

### ISSUE THREAD

**Issue by cwmke** [vector-im/riot-android#394] opened 2016-08-18 17:47 UTC
It would great to have an option to have the enter/send key submit the text instead of creating a new line. I know many other chat/sms apps offer this as an option in settings. Thanks for any consideration.

**Comment by sbts** [comment] 2017-06-12 03:56
This is definitely a duplicate of #220 can someone mark it as such please

**Closed** 2018-08-02 13:35 UTC
Labels: P3, enhancement
